version: "3.9"

services:
  videobot:
    build: .
    container_name: videobot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./downloads:/app/downloads
      - ./outputs:/app/outputs
